name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: good-pr:latest
      
      
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t good-pre:latest .
